[build]
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.19.0"
  NODE_ENV = "production"
  CI = "true"
  NPM_FLAGS = "--no-audit --no-optional"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[dev]
  framework = "vite"
  targetPort = 5173

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true
  target = "es2015"

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true